services:
  - type: web
    name: site-corrida-backend
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: DEFAULT_ADMIN_USER
        sync: false
      - key: DEFAULT_ADMIN_PASS
        sync: false
      - key: PORT
        value: "5000"
